name: on push
on:
  push:
    branch:
      -  "**"
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Run tests with maven
        working-directory: webdriver_java
        run: mvn test
          # handle remote server chromedriver